[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.intl", "composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "APP_ENV=prod php bin/console cache:clear",
  "APP_ENV=prod php bin/console cache:warmup"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"