controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

ziptag_uppercase:
    path: /Ziptag
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /ziptag
        permanent: true

ziptag_uppercase_slash:
    path: /Ziptag/
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /ziptag
        permanent: true
